FROM python
RUN pip install flask
COPY  Docker.py /home/myapp/
EXPOSE 8080
CMD python3 /home/myapp/Docker.py
FROM python
RUN pip install flask
COPY  docker.py /home/myapp/
EXPOSE 8080
CMD python3 /home/myapp/docker.py
